AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL DB in private subnets, password from SSM SecureString

Parameters:
  VpcId:
    Type: String
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String
  DBMasterPassword:
    Type: AWS::SSM::Parameter::Value<String>
    Description: SSM SecureString parameter with DB master password (e.g., /test/prod/db/pass)
    Default: /test/prod/db/pass
  DBMasterUsername:
    Type: String
    Default: admin
    Description: DB Master username

Resources:
  # Security Group for RDS (allow MySQL only from prod EC2)
  ProdRdsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL from prod EC2 only
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: ProdRdsSG

  # RDS Subnet Group (multi-AZ)
  ProdDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Prod RDS subnet group"
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: ProdDbSubnetGroup

  # RDS Instance
  ProdRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref ProdDbSubnetGroup
      VPCSecurityGroups:
        - !Ref ProdRdsSG
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      MultiAZ: true
      StorageEncrypted: true
      PubliclyAccessible: false
      DBName: prod_db
      DeletionProtection: false
      BackupRetentionPeriod: 7
      Tags:
        - Key: Name
          Value: ProdRDS

Outputs:
  RDSInstanceEndpoint:
    Value: !GetAtt ProdRDS.Endpoint.Address
    Description: RDS endpoint
  RDSInstanceId:
    Value: !Ref ProdRDS
    Description: RDS instance ID
  RDSDbName:
    Value: prod_db
    Description: Database name
